### ISSUE TITLE
关于高质量的插图替换

### ISSUE THREAD

**Issue by ShaunXyu** [jamesfang8499/physics1#4]
谢谢你的工作。我这里有人教社九十年代出版的《高中物理读本》3册的PDF，其内容是在甲种本的基础上稍作修订，扫描质量更好一些，可以用作插图的替换。链接如下：
链接：https://pan.baidu.com/s/13evpWwfZ1rwVFLxIJ8R8kA?pwd=phys
此外，我手上还有课标实验版高中物理（必修2册，选修3系列5册）的原版电子课本，内含矢量插图，亦可作为该项目的插图替换，如果你有意向，我再分享于你。

**Comment by jamesfang8499** [comment]
非常感谢您的分享，您所提及的原版电子课本，我已经从网盘上获得，文档中的很多矢量图来源于此。
